Feature/ss 407
lunasoft/sw-sdk-ruby pull request #14
Opened 2023-10-25 15:13 UTC by ReyesSW

Se realiza revision general de libreria y tambien se arreglan las UT. Se manda Feature.

2023-10-25 15:48 UTC, FerCarrilloM approved these changes

2023-10-25 16:05 UTC, SebastianSW approved these changes

2023-10-25 19:33 UTC, SwAeyrton requested changes
Falta subir la version.

2023-10-26 04:42 UTC, ReyesSW commented on Test/Sign/sign_test.rb
> +      assert(response.get_data.to_s.strip != "")
La modificación response.get_data.to_s.strip asegura que response.get_data se convierta en una cadena antes de aplicar strip, y luego se verifica si la cadena resultante no está vacía. Solo es para poder leer correctamente la respuesta, ya que mandaba el error:  Error: test_sign_success(SignTest): NoMethodError: undefined method `strip' for {"tfd"=> , que hace referencia a que es un objeto y no un string. Aun así es correcta la prueba, puesto que espera el success en el estatus.

2023-10-26 04:44 UTC, SwAeyrton commented on Test/Sign/sign_test.rb
> +      assert(response.get_data.to_s.strip != "")
va, sugiero validar tambien que no sea null para evitar un tema de null exception, si ya lo hace entonces asi queda, gracias Reyes

2023-10-26 05:01 UTC, SwAeyrton approved these changes

2023-10-26 05:06 UTC, ReyesSW commented on Test/Sign/sign_test.rb
> +      assert(response.get_data.to_s.strip != "")
Se añade validación dentro de la misma prueba, para que sea Success, no sea null ni tampoco un string vacio.

2023-10-26 05:06 UTC, ReyesSW commented on Test/AcceptReject/accept_reject_test.rb
> +        b64_csd = read_file('../../resources/b64_csd.txt')
Ya se añaden los recursos a la misma carpeta.

2023-10-26 05:09 UTC, merged